### ISSUE TITLE
README udpate

### ISSUE THREAD

**Issue by will-hu-0** [novaspirit/amdgpu-rocm-ubu22#2]
Hi, really appreciate the tutorial for installing AMD drivers into Ubuntu 22.04!
I have got my 6600XT running well.

just a typo in README.md

```
usermod -a -G vidoe $LOGNAME
```

I suppose it should be `video`.

BTW, what's the software you are showing in the page? Thanks!
![Selection_102](https://user-images.githubusercontent.com/4235291/185387522-e285b310-b7f6-4a7c-8e12-2e84f18a1817.png)

**Comment by novaspirit** [comment]
fixed, and the software used in screenshot is DaVinci Resolve 18
